# Server
server:
  port: 5000
  
# Spring
spring:
  
  application:
    name: MV
  jackson:
    date-format: "yyyy-MM-dd"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource: 
    url: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)))'
    username: system
    password: testpassword
  
